/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */                                                                    //Anant
#include <stdio.h>
#include <stdint.h>
#include "Led.h"

static void LEDON(void);
static void LEDOFF(void);
static void LEDONC(void);
static void LEDONAC(void);




static void LEDON(void)
{
	printf("Lock\n");
	led_on(LED_GREEN);
	led_on(LED_ORANGE);
	led_on(LED_RED);
	led_on(LED_BLUE);
}

static void LEDOFF(void)
{
	printf("Unlock\n");
	led_off(LED_GREEN);
	led_off(LED_ORANGE);
	led_off(LED_RED);
	led_off(LED_BLUE);
}





static void LEDONC(void)
{
	printf("Alarm Activation\n");
	led_on(LED_GREEN);
	delay(100);
	led_off(LED_GREEN);
	delay(100);
	led_on(LED_ORANGE);
	delay(100);
	led_off(LED_ORANGE);
	delay(100);
	led_on(LED_RED);
	delay(100);
	led_off(LED_RED);
	delay(100);
	led_on(LED_BLUE);
	delay(100);
	led_off(LED_BLUE);
}






static void LEDONAC(void)

{
	printf("Approach Light\n");
	led_on(LED_GREEN);
	delay(100);
	led_off(LED_GREEN);
	delay(100);
	led_on(LED_BLUE);
	delay(100);
	led_off(LED_BLUE);
	delay(100);
	led_on(LED_RED);
	delay(100);
	led_off(LED_RED);
	delay(100);
	led_on(LED_ORANGE);
	delay(100);
	led_off(LED_ORANGE);
}




int main(void)
{

	led_init_all();
	bluebutton_init();
	while (1)
	{
		int result;
		result = bluebutton_count();
		volatile int en1 = encryp(result);
		volatile int en2 = encryp(result);
		volatile int en3 = encryp(result);
		volatile int en4 = encryp(result);
		if (en1 == 5)
		{
			LEDON();
			result = 0;
		}
		else if (en2 == 6)
		{
			LEDOFF();
			result = 0;
		}
		else if (en3 == 7)
		{
			LEDONC();
			result = 0;
		}
		else if (en4 == 8)
		{
			LEDONAC();
			result = 0;
		}
	}
}
